# Generated by Django 4.0.5 on 2022-08-22 14:48

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('mobile_no', models.CharField(blank=True, db_column='mobile_no', max_length=20, null=True)),
                ('address', models.CharField(db_column='address', max_length=200, null=True)),
                ('city', models.CharField(blank=True, db_column='city', max_length=40)),
                ('profile_pic', models.FileField(db_column='profile_pic', null=True, upload_to='user/')),
                ('username', models.CharField(db_column='username', max_length=100, unique=True)),
                ('secret_code', models.CharField(db_column='secret_code', max_length=20)),
                ('qr_code', models.FileField(blank=True, db_column='qr_code', null=True, upload_to='bin/')),
                ('is_staff', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True, db_column='created_at', max_length=40)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', user.models.UserManager()),
            ],
        ),
    ]
